CREATE TABLE IF NOT EXISTS users(
	discordID VARCHAR(30) UNIQUE,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(discordID)
);
CREATE TABLE IF NOT EXISTS notes(
	id INTEGER UNIQUE AUTO_INCREMENT,
	discordID VARCHAR(30) NOT NULL,
	authorID VARCHAR(60) NOT NULL,
	noteID INTEGER NOT NULL DEFAULT 1,
	content TEXT NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(discordID) REFERENCES users(discordID),
	PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS articles(
	id INTEGER UNIQUE AUTO_INCREMENT,
	articleURL TEXT NOT NULL,
	discordID VARCHAR(30) NOT NULL,
	title VARCHAR(255) NOT NULL,
	articleDescription TEXT NOT NULL,
	views INTEGER NOT NULL DEFAULT 1,
	content TEXT NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	editedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(discordID) REFERENCES users(discordID),
	PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS forms(
	banID INTEGER UNIQUE,
	counter INTEGER,
	PRIMARY KEY(banID)
);