CREATE TABLE IF NOT EXISTS users(
    discordID VARCHAR(30) UNIQUE,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    PRIMARY KEY(discordID)
);
CREATE TABLE IF NOT EXISTS payments(
    id VARCHAR(30) UNIQUE,
    productID VARCHAR(255) NOT NULL,
    title VARCHAR(255) NOT NULL,
    price VARCHAR(10) NOT NULL,
    paymentChannel VARCHAR(20) NOT NULL,
    email VARCHAR(255) NOT NULL,
    steamID varchar(30) NOT NULL,
    steamUsername text NOT NULL,
    discordID VARCHAR(30) NOT NULL,
    date DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(discordID) REFERENCES users(discordID),
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS notes(
    id INTEGER UNIQUE AUTO_INCREMENT,
    discordID VARCHAR(30) NOT NULL,
    authorID VARCHAR(60) NOT NULL,
    noteID INTEGER NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(discordID) REFERENCES users(discordID),
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS articles(
    id INTEGER UNIQUE AUTO_INCREMENT,
    address TEXT NOT NULL,
    discordID VARCHAR(30) NOT NULL,
    title VARCHAR(255) NOT NULL,
    description TEXT NOT NULL,
    views INTEGER NOT NULL DEFAULT 1,
    content TEXT NOT NULL,
    createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    editedAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
    FOREIGN KEY(discordID) REFERENCES users(discordID),
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS bans(
    id INTEGER UNIQUE,
    counter INTEGER,
    PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS config(
    dKey VARCHAR(100) NOT NULL UNIQUE,
    dValue TEXT,
    PRIMARY KEY(dKey)
);