CREATE TABLE IF NOT EXISTS Users(
	discordID VARCHAR(30) UNIQUE,
	total INTEGER NOT NULL DEFAULT 0,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY(discordID)
);
CREATE TABLE IF NOT EXISTS Donates(
	id INTEGER UNIQUE AUTO_INCREMENT,
	amount INTEGER NOT NULL DEFAULT 0,
	discordID VARCHAR(30) NOT NULL,
	approved BOOLEAN NOT NULL DEFAULT 0,
	approver VARCHAR(30) NOT NULL DEFAULT "",
	donationType VARCHAR(10) NOT NULL DEFAULT "",
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(discordID) REFERENCES Users(discordID),
	PRIMARY KEY(id)
);
CREATE TABLE IF NOT EXISTS Notes(
	id INTEGER UNIQUE AUTO_INCREMENT,
	discordID VARCHAR(30) NOT NULL,
	authorID VARCHAR(60) NOT NULL,
	noteID INTEGER NOT NULL DEFAULT 1,
	content TEXT NOT NULL,
	createdAt DATETIME NOT NULL DEFAULT CURRENT_TIMESTAMP,
	FOREIGN KEY(discordID) REFERENCES Users(discordID),
	PRIMARY KEY(id)
);